workspace:
  base: /go
  path: src/github.com/serret887/ogle

pipeline:
  build:
    image: golang
    commands:
      - go get  golang.org/x/net/html
      - go get  github.com/onsi/ginkgo/ginkgo &&
      - go get github.com/onsi/gomega
      - go get
      - go build
      - go vet
      -  ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
